In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df_train = pd.read_csv('data//train.csv')
df_train.head()

id  gravity    ph  osmo  cond  urea  calc  target
0   0    1.013  6.19   443  14.8   124  1.45       0
1   1    1.025  5.40   703  23.6   394  4.18       0
2   2    1.009  6.13   371  24.5   159  9.04       0
3   3    1.021  4.91   442  20.8   398  6.63       1
4   4    1.021  5.53   874  17.8   385  2.21       1

In [3]:
df_test = pd.read_csv('data//test.csv')
df_test.head()

id  gravity    ph  osmo  cond  urea   calc
0  414    1.017  5.24   345  11.5   152   1.16
1  415    1.020  5.68   874  29.0   385   3.46
2  416    1.024  5.36   698  19.5   354  13.00
3  417    1.020  5.33   668  25.3   252   3.46
4  418    1.011  5.87   567  29.0   457   2.36

In [4]:
X1 = df_train.drop(['id', 'target'], axis = 1)

In [5]:
y1 = df_train['target']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size = 0.2, random_state = 42)

In [7]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression

In [8]:
LRmodel = LogisticRegression(random_state = 42)
LRmodel.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [9]:
y_pred = LRmodel.predict(X_test_scaled)

In [1]:
def print_score(clf, X_train,X_test, y_train, y_test, train = True):
  lb = preprocessing.LabelBinarizer()
  lb.fit(y_train)

  if train:
    res = clf.predict(X_train)
    print('Train Results\n')
    print('Accuracy Score: {0:.4f} \n'.format(accuracy_score(y_train, res)))
    print('Classification Report: \n{}\n'.format(classification_report(y_train, res)))
    print('Confusion Matrix: \n{}\n'.format(confusion_matrix(y_train, res)))
    print('ROC AUC: {0:.4f} \n'.format(roc_auc_score(lb.transform(y_train), lb.transform(res))))

    res = cross_val_score(clf, X_train, y_train, cv = 10, scoring = 'accuracy')
    print('Average Accuracy: \t {0:.4f}'.format(np.mean(res)))
    print('Accuracy SD: \t\t {0:.4f}'.format(np.std(res)))

  elif train == False:
    res_test = clf.predict(X_test)
    print('Test Results\n')
    print('Accuracy Score: {0:.4f} \n'.format(accuracy_score(y_test, res_test)))
    print('Classification Report: \n{}\n'.format(classification_report(y_test, res_test)))
    print('Confusion Matrix: \n{}\n'.format(confusion_matrix(y_test, res_test)))
    print('ROC AUC: {0:.4f} \n'.format(roc_auc_score(lb.transform(y_test), lb.transform(res_test))))

In [11]:
print_score(LRmodel, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(LRmodel, X_train, X_test, y_train, y_test, train = False)

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision

Train Results

Accuracy Score: 0.5589 

Classification Report: 
              precision    recall  f1-score   support

           0       0.56      1.00      0.72       185
           1       0.00      0.00      0.00       146

    accuracy                           0.56       331
   macro avg       0.28      0.50      0.36       331
weighted avg       0.31      0.56      0.40       331


Confusion Matrix: 
[[185   0]
 [146   0]]

ROC AUC: 0.5000 

Average Accuracy: 	 0.7099
Accuracy SD: 		 0.0669

 *****************************************************************

Test Results

Accuracy Score: 0.5422 

Classification Report: 
              precision    recall  f1-score   support

           0       0.54      1.00      0.70        45
           1       0.00      0.00      0.00        38

    accuracy                           0.54        83
   macro avg       0.27      0.50      0.35        83
weighted avg       0.29      0.54      0.38        83


Confusion Matrix: 
[[45  0]
 [38  0]]

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mode

# Decision Tree

In [12]:
DTmodel = DecisionTreeClassifier(random_state = 42)
DTmodel.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
y_pred = DTmodel.predict(X_test_scaled)

In [14]:
print_score(DTmodel, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(DTmodel, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.3505 

Classification Report: 
              precision    recall  f1-score   support

           0       0.44      0.56      0.49       185
           1       0.13      0.08      0.10       146

    accuracy                           0.35       331
   macro avg       0.28      0.32      0.30       331
weighted avg       0.30      0.35      0.32       331


Confusion Matrix: 
[[104  81]
 [134  12]]

ROC AUC: 0.3222 

Average Accuracy: 	 0.6767
Accuracy SD: 		 0.0429

 *****************************************************************

Test Results

Accuracy Score: 0.2289 

Classification Report: 
              precision    recall  f1-score   support

           0       0.31      0.36      0.33        45
           1       0.09      0.08      0.09        38

    accuracy                           0.23        83
   macro avg       0.20      0.22      0.21        83
weighted avg       0.21      0.23      0.22        83


Confusion Matrix: 
[[16 29]
 [35  3]]

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


# Random Forest Classifier

In [15]:
RFmodel = RandomForestClassifier(n_estimators=800, random_state=42, min_samples_leaf = 4, max_depth = 7, max_leaf_nodes = 9, max_samples = 10, min_samples_split = 10)
RFmodel.fit(X_train_scaled, y_train)

RandomForestClassifier(max_depth=7, max_leaf_nodes=9, max_samples=10,
                       min_samples_leaf=4, min_samples_split=10,
                       n_estimators=800, random_state=42)

In [16]:
y_pred = RFmodel.predict(X_test_scaled)

In [17]:
print_score(RFmodel, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(RFmodel, X_train, X_test, y_train, y_test, train = False)

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Preci

Train Results

Accuracy Score: 0.4411 

Classification Report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       185
           1       0.44      1.00      0.61       146

    accuracy                           0.44       331
   macro avg       0.22      0.50      0.31       331
weighted avg       0.19      0.44      0.27       331


Confusion Matrix: 
[[  0 185]
 [  0 146]]

ROC AUC: 0.5000 

Average Accuracy: 	 0.6858
Accuracy SD: 		 0.0705

 *****************************************************************

Test Results

Accuracy Score: 0.4578 

Classification Report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        45
           1       0.46      1.00      0.63        38

    accuracy                           0.46        83
   macro avg       0.23      0.50      0.31        83
weighted avg       0.21      0.46      0.29        83


Confusion Matrix: 
[[ 0 45]
 [ 0 38]]

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Preci

# SVM

In [18]:
SVMmodel = SVC(kernel='rbf', random_state=42)  # You can choose 'linear', 'poly', 'rbf', or 'sigmoid'
SVMmodel.fit(X_train_scaled, y_train)

SVC(random_state=42)

In [19]:
y_pred = SVMmodel.predict(X_test_scaled)

In [20]:
print_score(SVMmodel, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(SVMmodel, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.5589 

Classification Report: 
              precision    recall  f1-score   support

           0       0.56      1.00      0.72       185
           1       0.00      0.00      0.00       146

    accuracy                           0.56       331
   macro avg       0.28      0.50      0.36       331
weighted avg       0.31      0.56      0.40       331


Confusion Matrix: 
[[185   0]
 [146   0]]

ROC AUC: 0.5000 

Average Accuracy: 	 0.6075
Accuracy SD: 		 0.0713

 *****************************************************************

Test Results

Accuracy Score: 0.5422 

Classification Report: 
              precision    recall  f1-score   support

           0       0.54      1.00      0.70        45
           1       0.00      0.00      0.00        38

    accuracy                           0.54        83
   macro avg       0.27      0.50      0.35        83
weighted avg       0.29      0.54      0.38        83


Confusion Matrix: 
[[45  0]
 [38  0]]

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined

# K Nearest Neighbor

In [21]:
kmodel = KNeighborsClassifier(n_neighbors=1)
kmodel.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=1)

In [22]:
y_pred = kmodel.predict(X_test_scaled)

In [23]:
print_score(kmodel, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(kmodel, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.5589 

Classification Report: 
              precision    recall  f1-score   support

           0       0.56      1.00      0.72       185
           1       0.00      0.00      0.00       146

    accuracy                           0.56       331
   macro avg       0.28      0.50      0.36       331
weighted avg       0.31      0.56      0.40       331


Confusion Matrix: 
[[185   0]
 [146   0]]

ROC AUC: 0.5000 

Average Accuracy: 	 0.6072
Accuracy SD: 		 0.0836

 *****************************************************************

Test Results

Accuracy Score: 0.5422 

Classification Report: 
              precision    recall  f1-score   support

           0       0.54      1.00      0.70        45
           1       0.00      0.00      0.00        38

    accuracy                           0.54        83
   macro avg       0.27      0.50      0.35        83
weighted avg       0.29      0.54      0.38        83


Confusion Matrix: 
[[45  0]
 [38  0]]

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precisi

# XGBoost

In [24]:
model = XGBClassifier(eval_metric='mlogloss')
model.fit(X_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [25]:
y_pred = model.predict(X_test_scaled)

In [26]:
print_score(model, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(model, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.5589 

Classification Report: 
              precision    recall  f1-score   support

           0       0.56      1.00      0.72       185
           1       0.00      0.00      0.00       146

    accuracy                           0.56       331
   macro avg       0.28      0.50      0.36       331
weighted avg       0.31      0.56      0.40       331


Confusion Matrix: 
[[185   0]
 [146   0]]

ROC AUC: 0.5000 



C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

Average Accuracy: 	 0.6887
Accuracy SD: 		 0.0795

 *****************************************************************

Test Results

Accuracy Score: 0.5422 

Classification Report: 
              precision    recall  f1-score   support

           0       0.54      1.00      0.70        45
           1       0.00      0.00      0.00        38

    accuracy                           0.54        83
   macro avg       0.27      0.50      0.35        83
weighted avg       0.29      0.54      0.38        83


Confusion Matrix: 
[[45  0]
 [38  0]]

ROC AUC: 0.5000 



C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

# Neural Network Classifier

In [27]:
NNCmodel = Sequential()
NNCmodel.add(Dense(64, input_dim=X_train_scaled.shape[1], activation='relu'))  
NNCmodel.add(Dense(32, activation='relu'))  
NNCmodel.add(Dense(1, activation='sigmoid'))  

C:\Users\91740\anaconda3\envs\udemy_course\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
NNCmodel.compile(optimizer='Nadam', loss='binary_crossentropy', metrics=['accuracy']) # RMSprop, Adagrad, Adadelta, Adamax, Nadam

In [29]:
history = NNCmodel.fit(X_train_scaled, y_train, epochs=10, batch_size=32)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 8s 25ms/step - accuracy: 0.5921 - loss: 0.6709
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6710 - loss: 0.6214  
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6696 - loss: 0.6021 
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7093 - loss: 0.6099 
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7228 - loss: 0.5880 
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7459 - loss: 0.5731 
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7340 - loss: 0.5631 
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7557 - loss: 0.5616 
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7152 - loss: 0.5814 
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7374 - loss: 0.5484 


In [30]:
y_pred_prob = model.predict(X_test_scaled)
y_pred = (y_pred_prob > 0.5).astype(int).flatten()
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1])

# Grid Search

In [31]:
RFmodel.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 7,
 'max_features': 'sqrt',
 'max_leaf_nodes': 9,
 'max_samples': 10,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 4,
 'min_samples_split': 10,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 800,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [32]:
params = {# 'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          # 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         # 'max_leaf_nodes': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         # 'max_samples': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         # 'min_samples_split': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
         }

In [1]:
grid_search_cv = GridSearchCV(RandomForestClassifier(n_estimators=800, random_state=42, min_samples_leaf = 4, max_depth = 7, max_leaf_nodes = 9, max_samples = 10, min_samples_split = 10), params, cv = 10, n_jobs = -1, verbose = 1)

NameError: name 'GridSearchCV' is not defined

In [34]:
grid_search_cv.fit(X_train, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


GridSearchCV(cv=10,
             estimator=RandomForestClassifier(max_depth=7, max_leaf_nodes=9,
                                              max_samples=10,
                                              min_samples_leaf=4,
                                              min_samples_split=10,
                                              n_estimators=800,
                                              random_state=42),
             n_jobs=-1,
             param_grid={'n_estimators': [100, 200, 300, 400, 500, 600, 700,
                                          800, 900, 1000]},
             verbose=1)

In [35]:
grid_search_cv.best_estimator_

RandomForestClassifier(max_depth=7, max_leaf_nodes=9, max_samples=10,
                       min_samples_leaf=4, min_samples_split=10,
                       n_estimators=800, random_state=42)

In [36]:
print_score(grid_search_cv, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(grid_search_cv, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.6918 

Classification Report: 
              precision    recall  f1-score   support

           0       0.69      0.83      0.75       185
           1       0.70      0.52      0.60       146

    accuracy                           0.69       331
   macro avg       0.69      0.67      0.67       331
weighted avg       0.69      0.69      0.68       331


Confusion Matrix: 
[[153  32]
 [ 70  76]]

ROC AUC: 0.6738 

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates,

In [37]:
# params = {'n_jobs' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
grid_search_cv = GridSearchCV(SVC(), {'degree' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}, cv = 10, n_jobs = -1, verbose = 1)

In [38]:
grid_search_cv.fit(X_train, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'degree': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}, verbose=1)

In [39]:
grid_search_cv.best_estimator_

SVC(degree=1)

In [40]:
print_score(grid_search_cv, X_train, X_test, y_train, y_test, train = True)
print('\n *****************************************************************\n')
print_score(grid_search_cv, X_train, X_test, y_train, y_test, train = False)

Train Results

Accuracy Score: 0.6163 

Classification Report: 
              precision    recall  f1-score   support

           0       0.68      0.60      0.64       185
           1       0.56      0.64      0.59       146

    accuracy                           0.62       331
   macro avg       0.62      0.62      0.62       331
weighted avg       0.62      0.62      0.62       331


Confusion Matrix: 
[[111  74]
 [ 53  93]]

ROC AUC: 0.6185 

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates,